main: fr.xxathyx.mediaplayer.Main
name: MediaPlayer
version: 1.0.3
author: 650a
description: Allows you to play and use various medias on Minecraft.
website: https://github.com/650a/MediaPlayer/releases/latest/download/MediaPlayer.jar
api-version: 1.13

commands:
  mediaplayer:
    description: "MediaPlayer root command."
    aliases: [mp]
    permission: mediaplayer.command
permissions:
  mediaplayer.permission.admin:
    description: Provides access to various in-game admin tools.
  mediaplayer.command:
    description: Access to /mediaplayer.
  mediaplayer.screen.manage:
    description: Create/delete screens and set scaling.
  mediaplayer.playback:
    description: Control playback on screens.
  mediaplayer.admin:
    description: Reload MediaPlayer.
