main: com._650a.movietheatrecore.Main
name: MovieTheatreCore
version: 1.0.4
author: 650a
description: Multi-room cinema media playback for Minecraft servers.
website: https://b0x.us
api-version: 1.13

commands:
  movietheatrecore:
    description: "MovieTheatreCore root command."
    aliases: [mtc, theatre, mp]
    permission: movietheatrecore.command
permissions:
  movietheatrecore.permission.admin:
    description: Provides access to various in-game admin tools.
  movietheatrecore.command:
    description: Access to /movietheatrecore.
  movietheatrecore.screen.manage:
    description: Create/delete screens and set scaling.
  movietheatrecore.playback:
    description: Control playback on screens.
  movietheatrecore.admin:
    description: Reload MovieTheatreCore.
  movietheatrecore.media.manage:
    description: Manage cached media entries.
  movietheatrecore.media.admin:
    description: Add/remove URL-based media and play direct URLs.
  movietheatrecore.pack.manage:
    description: Manage internal resource pack hosting and rebuilds.
  movietheatrecore.deps.manage:
    description: Manage MovieTheatreCore dependency status and reinstalls.
  movietheatrecore.theatre.room.create:
    description: Create theatre rooms.
  movietheatrecore.theatre.room.delete:
    description: Delete theatre rooms.
  movietheatrecore.theatre.schedule.add:
    description: Add theatre schedule entries.
  movietheatrecore.theatre.schedule.remove:
    description: Remove theatre schedule entries.
  movietheatrecore.theatre.schedule.list:
    description: List theatre schedule entries.
  movietheatrecore.theatre.play:
    description: Start a theatre show in a room.
  movietheatrecore.theatre.stop:
    description: Stop a theatre show in a room.
  movietheatrecore.theatre.doctor:
    description: Run theatre self-check diagnostics.
