main: fr.xxathyx.mediaplayer.Main
name: MediaPlayer
version: 1.0.3
author: 650a
description: Allows you to play and use various medias on Minecraft.
website: https://github.com/650a/MediaPlayer/releases/latest/download/MediaPlayer.jar
api-version: 1.13

commands:
  mediaplayer:
    description: "MediaPlayer root command."
    aliases: [mp]
    permission: mediaplayer.command
permissions:
  mediaplayer.permission.admin:
    description: Provides access to various in-game admin tools.
  mediaplayer.command:
    description: Access to /mediaplayer.
  mediaplayer.screen.manage:
    description: Create/delete screens and set scaling.
  mediaplayer.playback:
    description: Control playback on screens.
  mediaplayer.admin:
    description: Reload MediaPlayer.
  mediaplayer.media.manage:
    description: Manage cached media entries.
  mediaplayer.media.admin:
    description: Add/remove URL-based media and play direct URLs.
  mediaplayer.pack.manage:
    description: Manage internal resource pack hosting and rebuilds.
  mediaplayer.deps.manage:
    description: Manage MediaPlayer dependency status and reinstalls.
  mediaplayer.theatre.room.create:
    description: Create theatre rooms.
  mediaplayer.theatre.room.delete:
    description: Delete theatre rooms.
  mediaplayer.theatre.schedule.add:
    description: Add theatre schedule entries.
  mediaplayer.theatre.schedule.remove:
    description: Remove theatre schedule entries.
  mediaplayer.theatre.schedule.list:
    description: List theatre schedule entries.
  mediaplayer.theatre.play:
    description: Start a theatre show in a room.
  mediaplayer.theatre.stop:
    description: Stop a theatre show in a room.
  mediaplayer.theatre.doctor:
    description: Run theatre self-check diagnostics.
